# Site settings
title: Jithin D. George
email: jithindg@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a masters student in the Department of Applied Mathematics at the University of Washington.
 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://dirivian.github.io" # the base hostname & protocol for your site
github_username:  Dirivian
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
theme: jekyll-theme-minimal
