# Site settings
title: Jithin D. George
email: jithindg@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  Ph.D candidate in the Department of Engineering Sciences and Applied Mathematics at Northwestern University. Previously, at the University of Washington.

# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://dirivian.github.io" # the base hostname & protocol for your site
github_username:  Dirivian
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
theme: minima #jekyll-theme-minimal
